[package]
name = "translate-bot"
version = "0.1.0"
authors = ["Ben Lovy <bendlovy@gmail.com>"]

[dependencies]
dotenv = "0.10"
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1"
serde_json = "1.0"
tokio-core = "0.1"
